# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exabel/api/management/v1/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exabel/api/management/v1/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .....protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&exabel/api/management/v1/service.proto\x12\x18\x65xabel.api.management.v1\x1a.protoc_gen_openapiv2/options/annotations.protoB\xaf\x03\n\x1c\x63om.exabel.api.management.v1B\x0cServiceProtoP\x01Z\x1c\x65xabel.com/api/management/v1\x92\x41\xdf\x02\x12U\n\x15\x45xabel Management API\"5\n\x06\x45xabel\x12\x17https://www.exabel.com/\x1a\x12support@exabel.com2\x05\x31.0.0\x1a\x19management.api.exabel.com*\x01\x02\x32\x10\x61pplication/json:\x10\x61pplication/jsonZR\n#\n\x07\x41PI key\x12\x18\x08\x02\x12\x07\x41PI key\x1a\tx-api-key \x02\n+\n\x06\x42\x65\x61rer\x12!\x08\x02\x12\x0c\x41\x63\x63\x65ss token\x1a\rauthorization \x02\x62\r\n\x0b\n\x07\x41PI key\x12\x00\x62\x0c\n\n\n\x06\x42\x65\x61rer\x12\x00rS\n$More about the Exabel Management API\x12+https://help.exabel.com/docs/management-apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exabel.api.management.v1.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.exabel.api.management.v1B\014ServiceProtoP\001Z\034exabel.com/api/management/v1\222A\337\002\022U\n\025Exabel Management API\"5\n\006Exabel\022\027https://www.exabel.com/\032\022support@exabel.com2\0051.0.0\032\031management.api.exabel.com*\001\0022\020application/json:\020application/jsonZR\n#\n\007API key\022\030\010\002\022\007API key\032\tx-api-key \002\n+\n\006Bearer\022!\010\002\022\014Access token\032\rauthorization \002b\r\n\013\n\007API key\022\000b\014\n\n\n\006Bearer\022\000rS\n$More about the Exabel Management API\022+https://help.exabel.com/docs/management-api'
# @@protoc_insertion_point(module_scope)
