"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2022 Exabel AS. All rights reserved."""

from collections import abc as _abc
from . import user_messages_pb2 as _user_messages_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ListGroupsRequest(_message.Message):
    """Request to ListGroups."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListGroupsRequest: _TypeAlias = ListGroupsRequest  # noqa: Y015

@_typing.final
class ListGroupsResponse(_message.Message):
    """Response from ListGroups."""

    DESCRIPTOR: _descriptor.Descriptor

    GROUPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def groups(self) -> _containers.RepeatedCompositeFieldContainer[_user_messages_pb2.Group]:
        """List of user groups, including users in each user group."""

    def __init__(
        self,
        *,
        groups: _abc.Iterable[_user_messages_pb2.Group] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["groups", b"groups"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListGroupsResponse: _TypeAlias = ListGroupsResponse  # noqa: Y015

@_typing.final
class ListUsersRequest(_message.Message):
    """Request to ListUsers."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___ListUsersRequest: _TypeAlias = ListUsersRequest  # noqa: Y015

@_typing.final
class ListUsersResponse(_message.Message):
    """Response from ListUsers."""

    DESCRIPTOR: _descriptor.Descriptor

    USERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def users(self) -> _containers.RepeatedCompositeFieldContainer[_user_messages_pb2.User]:
        """List of users."""

    def __init__(
        self,
        *,
        users: _abc.Iterable[_user_messages_pb2.User] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["users", b"users"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListUsersResponse: _TypeAlias = ListUsersResponse  # noqa: Y015
