"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2019-2025 Exabel AS. All rights reserved."""

import builtins
from ...time import date_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
from ..... import exabel

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Frequency:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _FrequencyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Frequency.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    FREQUENCY_UNSPECIFIED: _Frequency.ValueType  # 0
    """The frequency of the fiscal period is unspecified."""
    QUARTERLY: _Frequency.ValueType  # 1
    """The fiscal period is quarterly."""
    SEMIANNUAL: _Frequency.ValueType  # 2
    """The fiscal period is semi-annual."""
    ANNUAL: _Frequency.ValueType  # 3
    """The fiscal periods is annual."""

class Frequency(_Frequency, metaclass=_FrequencyEnumTypeWrapper):
    """The frequency of a fiscal period."""

FREQUENCY_UNSPECIFIED: Frequency.ValueType  # 0
"""The frequency of the fiscal period is unspecified."""
QUARTERLY: Frequency.ValueType  # 1
"""The fiscal period is quarterly."""
SEMIANNUAL: Frequency.ValueType  # 2
"""The fiscal period is semi-annual."""
ANNUAL: Frequency.ValueType  # 3
"""The fiscal periods is annual."""
global___Frequency = Frequency

@typing.final
class FiscalPeriod(google.protobuf.message.Message):
    """A fiscal period of a company."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FREQUENCY_FIELD_NUMBER: builtins.int
    START_DATE_FIELD_NUMBER: builtins.int
    END_DATE_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    IS_REPORTED_FIELD_NUMBER: builtins.int
    frequency: global___Frequency.ValueType
    """The frequency of the fiscal period."""
    label: builtins.str
    """The period label (e.g., "4Q-2025", "2H-2025", "FY-2025")."""
    is_reported: builtins.bool
    """Whether the period has been reported (earnings released)."""
    @property
    def start_date(self) -> exabel.api.time.date_pb2.Date:
        """The first date of the fiscal period."""

    @property
    def end_date(self) -> exabel.api.time.date_pb2.Date:
        """The last date in the fiscal period."""

    def __init__(
        self,
        *,
        frequency: global___Frequency.ValueType | None = ...,
        start_date: exabel.api.time.date_pb2.Date | None = ...,
        end_date: exabel.api.time.date_pb2.Date | None = ...,
        label: builtins.str | None = ...,
        is_reported: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end_date", b"end_date", "start_date", b"start_date"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end_date", b"end_date", "frequency", b"frequency", "is_reported", b"is_reported", "label", b"label", "start_date", b"start_date"]) -> None: ...

global___FiscalPeriod = FiscalPeriod
