"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2019-2022 Exabel AS. All rights reserved."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SearchUniverse:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SearchUniverseEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SearchUniverse.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SEARCH_UNIVERSE_UNSPECIFIED: _SearchUniverse.ValueType  # 0
    """No search universe specified. This is the default behaviour.
    For text search for entityTypes/company, this searches the Exabel company universe.
    """
    EXABEL_COMPANIES: _SearchUniverse.ValueType  # 1
    """Search all companies in the Exabel company universe. This includes all companies with
    price data or a directly connected time series. Only supported for text search for
    entityTypes/company.
    """
    ALL_COMPANIES: _SearchUniverse.ValueType  # 2
    """Search all companies, including companies not in the Exabel company universe. This includes all
    FactSet companies of type 'SUB' and 'PVT'. Only supported for text search for entityTypes/company.
    """

class SearchUniverse(_SearchUniverse, metaclass=_SearchUniverseEnumTypeWrapper):
    """Enum to select search universe."""

SEARCH_UNIVERSE_UNSPECIFIED: SearchUniverse.ValueType  # 0
"""No search universe specified. This is the default behaviour.
For text search for entityTypes/company, this searches the Exabel company universe.
"""
EXABEL_COMPANIES: SearchUniverse.ValueType  # 1
"""Search all companies in the Exabel company universe. This includes all companies with
price data or a directly connected time series. Only supported for text search for
entityTypes/company.
"""
ALL_COMPANIES: SearchUniverse.ValueType  # 2
"""Search all companies, including companies not in the Exabel company universe. This includes all
FactSet companies of type 'SUB' and 'PVT'. Only supported for text search for entityTypes/company.
"""
Global___SearchUniverse: _TypeAlias = SearchUniverse  # noqa: Y015

@_typing.final
class SearchTerm(_message.Message):
    """A single search term in a search request."""

    DESCRIPTOR: _descriptor.Descriptor

    FIELD_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    field: _builtins.str
    """The name of the field that should be matched. Field names are
    case-insensitive.
    """
    query: _builtins.str
    """The query against which the field is matched."""
    def __init__(
        self,
        *,
        field: _builtins.str | None = ...,
        query: _builtins.str | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["field", b"field", "query", b"query"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchTerm: _TypeAlias = SearchTerm  # noqa: Y015

@_typing.final
class SearchOptions(_message.Message):
    """Options on how the search should be performed."""

    DESCRIPTOR: _descriptor.Descriptor

    UNIVERSE_FIELD_NUMBER: _builtins.int
    universe: Global___SearchUniverse.ValueType
    """The entity universe to search. Currently only supported for 'text' search for entityType/company."""
    def __init__(
        self,
        *,
        universe: Global___SearchUniverse.ValueType | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["universe", b"universe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___SearchOptions: _TypeAlias = SearchOptions  # noqa: Y015
