#!/usr/bin/env bash

# Builds the files for distribution and uploads them to PyPI, provided that:
#   - You are on the main branch and there are no uncommitted changes.
#   - All the style checks run without errors.
#   - All the tests run without errors.
#
# By default, the script uploads to Test PyPI (test.pypi.org); to upload to the real PyPI, run with
# the argument --real-pypi.
#
# Use --force to skip branch and uncommitted changes checks (only allowed for Test PyPI).
#
# Any additional arguments (e.g. --dry-run) are forwarded to uv publish.
#
# The environment variable UV_PUBLISH_TOKEN must be set to the token generated by PyPI for the
# account.

set -euf

UPLOAD_TO_REAL_PYPI=false
FORCE=false
EXTRA_ARGS=()

for arg in "$@"; do
  case "${arg}" in
    --real-pypi)
      UPLOAD_TO_REAL_PYPI=true
      ;;
    --force)
      FORCE=true
      ;;
    *)
      EXTRA_ARGS+=("${arg}")
      ;;
  esac
done

if [ "${FORCE}" == true ] && [ "${UPLOAD_TO_REAL_PYPI}" == true ]; then
  echo "--force can only be used when publishing to Test PyPI."
  exit 1
fi

if [ "${FORCE}" != true ]; then
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if [[ "${BRANCH}" != "main" ]]; then
    echo "You can only publish from the main branch, but you are currently on '${BRANCH}'."
    exit 1;
  fi

  if [ "$(git status --porcelain)" ]; then
    echo "You have uncommitted changes. Clean them up before publishing."
    exit 1;
  fi
fi

bash build.sh
if [ -z "${UV_PUBLISH_TOKEN:-}" ]; then
  echo "UV_PUBLISH_TOKEN is not set. Export it before publishing."
  exit 1
fi

if [ "${UPLOAD_TO_REAL_PYPI}" == true ]; then
  PUBLISH_INDEX="PyPI (https://pypi.org)"
else
  PUBLISH_INDEX="Test PyPI (https://test.pypi.org)"
fi

echo ""
echo "About to publish to: ${PUBLISH_INDEX}"
if [ ${#EXTRA_ARGS[@]} -gt 0 ]; then
  echo "Extra arguments: ${EXTRA_ARGS[*]}"
fi
read -r -p "Do you want to continue? [y/N] " confirm
if [[ "${confirm}" != [yY] ]]; then
  echo "Aborted."
  exit 0
fi

if [ "${UPLOAD_TO_REAL_PYPI}" == true ]; then
  echo ""
  echo "=== Publishing package to the real PyPI ==="
  uv publish "${EXTRA_ARGS[@]}"
else
  echo "Publishing to test"
  uv publish --publish-url https://test.pypi.org/legacy/ "${EXTRA_ARGS[@]}"
  echo ""
  echo "To install from Test PyPI:"
  echo "  create a virtual environment in an empty directory"
  echo "  uv venv .venv"
  echo "  source .venv/bin/activate"
  echo "  uv pip install --index https://test.pypi.org/simple/ exabel"
fi
