#!/usr/bin/env bash

# Runs the style checks and tests, builds the files for distribution and uploads them to PyPI.
#
# By default, uploads to test PyPI; to upload to the real PyPI, run with the argument -r.
#
# In either case, you will be asked for username and password. The username should be __token__,
# while the password is the token generated by PyPI for the account.

set -e

UPLOAD_TO_REAL_PYPI=false

while getopts 'r' c; do
  case $c in
    r)
      UPLOAD_TO_REAL_PYPI=true
      ;;
  esac
done

bash build.sh
if [ $# -eq 0 ]; then
  python3 -m twine upload --repository testpypi dist/*
else
  echo ""
  echo "=== Publishing package the real PyPI ==="
  python3 -m twine upload dist/*
fi
