"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class Http(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    fully_decode_reserved_expansion: builtin___bool = ...

    @property
    def rules(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___HttpRule]: ...

    def __init__(self,
        *,
        rules : typing___Optional[typing___Iterable[type___HttpRule]] = None,
        fully_decode_reserved_expansion : typing___Optional[builtin___bool] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"fully_decode_reserved_expansion",b"fully_decode_reserved_expansion",u"rules",b"rules"]) -> None: ...
type___Http = Http

class HttpRule(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    selector: typing___Text = ...
    get: typing___Text = ...
    put: typing___Text = ...
    post: typing___Text = ...
    delete: typing___Text = ...
    patch: typing___Text = ...
    body: typing___Text = ...
    response_body: typing___Text = ...

    @property
    def custom(self) -> type___CustomHttpPattern: ...

    @property
    def additional_bindings(self) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[type___HttpRule]: ...

    def __init__(self,
        *,
        selector : typing___Optional[typing___Text] = None,
        get : typing___Optional[typing___Text] = None,
        put : typing___Optional[typing___Text] = None,
        post : typing___Optional[typing___Text] = None,
        delete : typing___Optional[typing___Text] = None,
        patch : typing___Optional[typing___Text] = None,
        custom : typing___Optional[type___CustomHttpPattern] = None,
        body : typing___Optional[typing___Text] = None,
        response_body : typing___Optional[typing___Text] = None,
        additional_bindings : typing___Optional[typing___Iterable[type___HttpRule]] = None,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions___Literal[u"custom",b"custom",u"delete",b"delete",u"get",b"get",u"patch",b"patch",u"pattern",b"pattern",u"post",b"post",u"put",b"put"]) -> builtin___bool: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"additional_bindings",b"additional_bindings",u"body",b"body",u"custom",b"custom",u"delete",b"delete",u"get",b"get",u"patch",b"patch",u"pattern",b"pattern",u"post",b"post",u"put",b"put",u"response_body",b"response_body",u"selector",b"selector"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions___Literal[u"pattern",b"pattern"]) -> typing_extensions___Literal["get","put","post","delete","patch","custom"]: ...
type___HttpRule = HttpRule

class CustomHttpPattern(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    kind: typing___Text = ...
    path: typing___Text = ...

    def __init__(self,
        *,
        kind : typing___Optional[typing___Text] = None,
        path : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"kind",b"kind",u"path",b"path"]) -> None: ...
type___CustomHttpPattern = CustomHttpPattern
