DEFAULT_ABORT_THRESHOLD = 0.5
DEFAULT_BULK_LOAD_CHECKPOINTS = 10
DEFAULT_NUMBER_OF_THREADS = 40
DEFAULT_NUMBER_OF_THREADS_FOR_IMPORT = 4
DEFAULT_NUMBER_OF_RETRIES = 5
MAX_THREADS_FOR_IMPORT = 100
FAILURE_LOG_LIMIT = None  # type: ignore[var-annotated]
