"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2024 Exabel AS. All rights reserved."""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Change:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ChangeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Change.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CHANGE_UNSPECIFIED: _Change.ValueType
    'Change is unspecified and invalid.'
    RELATIVE: _Change.ValueType
    'Change should be calculated relative to the previous value. (Default.)'
    ABSOLUTE: _Change.ValueType
    'Change should be calculated in absolute terms to the previous value.'

class Change(_Change, metaclass=_ChangeEnumTypeWrapper):
    """Defines the possible methods to calculate change."""
CHANGE_UNSPECIFIED: Change.ValueType
'Change is unspecified and invalid.'
RELATIVE: Change.ValueType
'Change should be calculated relative to the previous value. (Default.)'
ABSOLUTE: Change.ValueType
'Change should be calculated in absolute terms to the previous value.'
global___Change = Change