# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exabel/api/data/v1/time_series_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

from exabel_data_sdk.stubs.exabel.api.time import (
    time_range_pb2 as exabel_dot_api_dot_time_dot_time__range__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="exabel/api/data/v1/time_series_messages.proto",
    package="exabel.api.data.v1",
    syntax="proto3",
    serialized_options=b"\n\026com.exabel.api.data.v1B\027TimeSeriesMessagesProtoP\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n-exabel/api/data/v1/time_series_messages.proto\x12\x12\x65xabel.api.data.v1\x1a exabel/api/time/time_range.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto"b\n\nTimeSeries\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x33\n\x06points\x18\x02 \x03(\x0b\x32#.exabel.api.data.v1.TimeSeriesPoint\x12\x11\n\tread_only\x18\x03 \x01(\x08"h\n\x0fTimeSeriesPoint\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x05value\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue"@\n\x0eTimeSeriesView\x12.\n\ntime_range\x18\x01 \x01(\x0b\x32\x1a.exabel.api.time.TimeRangeB3\n\x16\x63om.exabel.api.data.v1B\x17TimeSeriesMessagesProtoP\x01\x62\x06proto3',
    dependencies=[
        exabel_dot_api_dot_time_dot_time__range__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,
    ],
)


_TIMESERIES = _descriptor.Descriptor(
    name="TimeSeries",
    full_name="exabel.api.data.v1.TimeSeries",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="exabel.api.data.v1.TimeSeries.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="points",
            full_name="exabel.api.data.v1.TimeSeries.points",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="read_only",
            full_name="exabel.api.data.v1.TimeSeries.read_only",
            index=2,
            number=3,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=168,
    serialized_end=266,
)


_TIMESERIESPOINT = _descriptor.Descriptor(
    name="TimeSeriesPoint",
    full_name="exabel.api.data.v1.TimeSeriesPoint",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="time",
            full_name="exabel.api.data.v1.TimeSeriesPoint.time",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="exabel.api.data.v1.TimeSeriesPoint.value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=268,
    serialized_end=372,
)


_TIMESERIESVIEW = _descriptor.Descriptor(
    name="TimeSeriesView",
    full_name="exabel.api.data.v1.TimeSeriesView",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="time_range",
            full_name="exabel.api.data.v1.TimeSeriesView.time_range",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=374,
    serialized_end=438,
)

_TIMESERIES.fields_by_name["points"].message_type = _TIMESERIESPOINT
_TIMESERIESPOINT.fields_by_name[
    "time"
].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_TIMESERIESPOINT.fields_by_name[
    "value"
].message_type = google_dot_protobuf_dot_wrappers__pb2._DOUBLEVALUE
_TIMESERIESVIEW.fields_by_name[
    "time_range"
].message_type = exabel_dot_api_dot_time_dot_time__range__pb2._TIMERANGE
DESCRIPTOR.message_types_by_name["TimeSeries"] = _TIMESERIES
DESCRIPTOR.message_types_by_name["TimeSeriesPoint"] = _TIMESERIESPOINT
DESCRIPTOR.message_types_by_name["TimeSeriesView"] = _TIMESERIESVIEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeSeries = _reflection.GeneratedProtocolMessageType(
    "TimeSeries",
    (_message.Message,),
    {
        "DESCRIPTOR": _TIMESERIES,
        "__module__": "exabel.api.data.v1.time_series_messages_pb2"
        # @@protoc_insertion_point(class_scope:exabel.api.data.v1.TimeSeries)
    },
)
_sym_db.RegisterMessage(TimeSeries)

TimeSeriesPoint = _reflection.GeneratedProtocolMessageType(
    "TimeSeriesPoint",
    (_message.Message,),
    {
        "DESCRIPTOR": _TIMESERIESPOINT,
        "__module__": "exabel.api.data.v1.time_series_messages_pb2"
        # @@protoc_insertion_point(class_scope:exabel.api.data.v1.TimeSeriesPoint)
    },
)
_sym_db.RegisterMessage(TimeSeriesPoint)

TimeSeriesView = _reflection.GeneratedProtocolMessageType(
    "TimeSeriesView",
    (_message.Message,),
    {
        "DESCRIPTOR": _TIMESERIESVIEW,
        "__module__": "exabel.api.data.v1.time_series_messages_pb2"
        # @@protoc_insertion_point(class_scope:exabel.api.data.v1.TimeSeriesView)
    },
)
_sym_db.RegisterMessage(TimeSeriesView)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
