"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2022-2024 Exabel AS. All rights reserved."""

from ...data.v1 import common_messages_pb2 as _common_messages_pb2
from ...math import aggregation_pb2 as _aggregation_pb2
from ...math import change_pb2 as _change_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _DerivedSignalUnit:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DerivedSignalUnitEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DerivedSignalUnit.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DERIVED_SIGNAL_UNIT_INVALID: _DerivedSignalUnit.ValueType  # 0
    """Signal unit was not specified."""
    NUMBER: _DerivedSignalUnit.ValueType  # 1
    """Signal represents normal floating point numbers. This is the default value."""
    RATIO: _DerivedSignalUnit.ValueType  # 2
    """Signal represents a ratio, typically with values in the interval [0, 1]. Values will be
    displayed as a percentage.
    """
    RATIO_DIFFERENCE: _DerivedSignalUnit.ValueType  # 3
    """Signal represents a difference in a ratio. Values will be displayed as percentage points."""

class DerivedSignalUnit(_DerivedSignalUnit, metaclass=_DerivedSignalUnitEnumTypeWrapper):
    """Unit of the signal."""

DERIVED_SIGNAL_UNIT_INVALID: DerivedSignalUnit.ValueType  # 0
"""Signal unit was not specified."""
NUMBER: DerivedSignalUnit.ValueType  # 1
"""Signal represents normal floating point numbers. This is the default value."""
RATIO: DerivedSignalUnit.ValueType  # 2
"""Signal represents a ratio, typically with values in the interval [0, 1]. Values will be
displayed as a percentage.
"""
RATIO_DIFFERENCE: DerivedSignalUnit.ValueType  # 3
"""Signal represents a difference in a ratio. Values will be displayed as percentage points."""
Global___DerivedSignalUnit: _TypeAlias = DerivedSignalUnit  # noqa: Y015

class _DerivedSignalType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DerivedSignalTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DerivedSignalType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DERIVED_SIGNAL_TYPE_INVALID: _DerivedSignalType.ValueType  # 0
    """Signal type was not specified."""
    DERIVED_SIGNAL: _DerivedSignalType.ValueType  # 1
    """Signal is a derived signal, with an editable label and expression. This is the default value."""
    FILE_UPLOADED_SIGNAL: _DerivedSignalType.ValueType  # 2
    """Signal uploaded through the legacy File Uploader. The expression refers to a raw signal and
    cannot be modified.
    """
    FILE_UPLOADED_COMPANY_SIGNAL: _DerivedSignalType.ValueType  # 3
    """Signal uploaded through the legacy File Uploader. The expression refers to a raw signal and
    cannot be modified.
    """
    PERSISTED_SIGNAL: _DerivedSignalType.ValueType  # 4
    """A persisted signal that is evaluated and cached daily.
    The expression refers to a raw signal and cannot be modified.
    """

class DerivedSignalType(_DerivedSignalType, metaclass=_DerivedSignalTypeEnumTypeWrapper):
    """Type of the signal. Not relevant for external use."""

DERIVED_SIGNAL_TYPE_INVALID: DerivedSignalType.ValueType  # 0
"""Signal type was not specified."""
DERIVED_SIGNAL: DerivedSignalType.ValueType  # 1
"""Signal is a derived signal, with an editable label and expression. This is the default value."""
FILE_UPLOADED_SIGNAL: DerivedSignalType.ValueType  # 2
"""Signal uploaded through the legacy File Uploader. The expression refers to a raw signal and
cannot be modified.
"""
FILE_UPLOADED_COMPANY_SIGNAL: DerivedSignalType.ValueType  # 3
"""Signal uploaded through the legacy File Uploader. The expression refers to a raw signal and
cannot be modified.
"""
PERSISTED_SIGNAL: DerivedSignalType.ValueType  # 4
"""A persisted signal that is evaluated and cached daily.
The expression refers to a raw signal and cannot be modified.
"""
Global___DerivedSignalType: _TypeAlias = DerivedSignalType  # noqa: Y015

@_typing.final
class DerivedSignal(_message.Message):
    """A derived signal.

    As opposed to raw signals which represents time series on entities, a derived signal
    represents a calculation through a DSL expression.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    EXPRESSION_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Unique resource name of the derived signal, e.g. `derivedSignals/123`. In the "Create derived
    signal" method, this is ignored and may be left empty.
    """
    label: _builtins.str
    """Label of the derived signal. This appears in the Library when browsing for derived signals,
    and when a derived signal is used in any Exabel feature (e.g. chart, dashboard). It can also
    be used to reference this derived signal in a second derived signal.

    This is required when creating a derived signal. Must be a valid Python identifier between
    1-100 characters, match the regex `^[a-zA-Z_]\\w{0,99}$`, and cannot be a Python keyword.
    """
    expression: _builtins.str
    """A DSL expression describing the signal transformations to apply. For more information, see the
    DSL reference.
    """
    description: _builtins.str
    """Appears in the Exabel Library, when browsing for derived signals."""
    display_name: _builtins.str
    """The human readable name of the signal."""
    @_builtins.property
    def metadata(self) -> Global___DerivedSignalMetadata:
        """Additional metadata to control formatting (decimals and units)."""

    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
        label: _builtins.str | None = ...,
        expression: _builtins.str | None = ...,
        description: _builtins.str | None = ...,
        display_name: _builtins.str | None = ...,
        metadata: Global___DerivedSignalMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["metadata", b"metadata"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "display_name", b"display_name", "expression", b"expression", "label", b"label", "metadata", b"metadata", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DerivedSignal: _TypeAlias = DerivedSignal  # noqa: Y015

@_typing.final
class DerivedSignalMetadata(_message.Message):
    """Additional metadata to control formatting (decimals and units).

    Note: this is only used today when a signal is added to a dashboard table. This will be phased
    out in favour of providing formatting controls in the Exabel features (charts, dashboards, etc.)
    where signals are used.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DECIMALS_FIELD_NUMBER: _builtins.int
    UNIT_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    DOWNSAMPLING_METHOD_FIELD_NUMBER: _builtins.int
    CHANGE_FIELD_NUMBER: _builtins.int
    ENTITY_SET_FIELD_NUMBER: _builtins.int
    unit: Global___DerivedSignalUnit.ValueType
    """Unit of the signal."""
    type: Global___DerivedSignalType.ValueType
    """Type of the signal. Not relevant for external use."""
    downsampling_method: _aggregation_pb2.Aggregation.ValueType
    """The default downsampling method to use when this signal is re-sampled into larger intervals.
    When two or more values in an interval needs to be aggregated into a single value, specifies
    how they are combined.
    """
    change: _change_pb2.Change.ValueType
    """The method used to calculate changes in this signal."""
    @_builtins.property
    def decimals(self) -> _wrappers_pb2.Int32Value:
        """Number of decimals to use when displaying numeric values."""

    @_builtins.property
    def entity_set(self) -> _common_messages_pb2.EntitySet:
        """The set of entities that this signal is valid for."""

    def __init__(
        self,
        *,
        decimals: _wrappers_pb2.Int32Value | None = ...,
        unit: Global___DerivedSignalUnit.ValueType | None = ...,
        type: Global___DerivedSignalType.ValueType | None = ...,
        downsampling_method: _aggregation_pb2.Aggregation.ValueType | None = ...,
        change: _change_pb2.Change.ValueType | None = ...,
        entity_set: _common_messages_pb2.EntitySet | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["decimals", b"decimals", "entity_set", b"entity_set"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["change", b"change", "decimals", b"decimals", "downsampling_method", b"downsampling_method", "entity_set", b"entity_set", "type", b"type", "unit", b"unit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DerivedSignalMetadata: _TypeAlias = DerivedSignalMetadata  # noqa: Y015
