# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exabel/api/analytics/v1/item_messages.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exabel/api/analytics/v1/item_messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+exabel/api/analytics/v1/item_messages.proto\x12\x17\x65xabel.api.analytics.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x01\n\x0cItemMetadata\x12\x34\n\x0b\x63reate_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03\x12\x34\n\x0bupdate_time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampB\x03\xe0\x41\x03\x12\x17\n\ncreated_by\x18\x03 \x01(\tB\x03\xe0\x41\x03\x12\x17\n\nupdated_by\x18\x04 \x01(\tB\x03\xe0\x41\x03\x12\x1e\n\x0cwrite_access\x18\x05 \x01(\x08\x42\x03\xe0\x41\x03H\x00\x88\x01\x01\x42\x0f\n\r_write_accessBO\n\x1b\x63om.exabel.api.analytics.v1B\x11ItemMessagesProtoP\x01Z\x1b\x65xabel.com/api/analytics/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exabel.api.analytics.v1.item_messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.exabel.api.analytics.v1B\021ItemMessagesProtoP\001Z\033exabel.com/api/analytics/v1'
  _globals['_ITEMMETADATA'].fields_by_name['create_time']._loaded_options = None
  _globals['_ITEMMETADATA'].fields_by_name['create_time']._serialized_options = b'\340A\003'
  _globals['_ITEMMETADATA'].fields_by_name['update_time']._loaded_options = None
  _globals['_ITEMMETADATA'].fields_by_name['update_time']._serialized_options = b'\340A\003'
  _globals['_ITEMMETADATA'].fields_by_name['created_by']._loaded_options = None
  _globals['_ITEMMETADATA'].fields_by_name['created_by']._serialized_options = b'\340A\003'
  _globals['_ITEMMETADATA'].fields_by_name['updated_by']._loaded_options = None
  _globals['_ITEMMETADATA'].fields_by_name['updated_by']._serialized_options = b'\340A\003'
  _globals['_ITEMMETADATA'].fields_by_name['write_access']._loaded_options = None
  _globals['_ITEMMETADATA'].fields_by_name['write_access']._serialized_options = b'\340A\003'
  _globals['_ITEMMETADATA']._serialized_start=139
  _globals['_ITEMMETADATA']._serialized_end=360
# @@protoc_insertion_point(module_scope)
