"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2025 Exabel AS. All rights reserved."""

from collections import abc as _abc
from . import kpi_messages_pb2 as _kpi_messages_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ListKpiMappingResultsRequest(_message.Message):
    """Request to ListKpiMappingResults."""

    DESCRIPTOR: _descriptor.Descriptor

    PARENT_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    parent: _builtins.str
    """Resource name of the KPI mapping to list results of.
    Example: `kpiMappings/123`.
    """
    page_size: _builtins.int
    """Maximum number of companies to return. Defaults to 20, and the maximum allowed value is 100."""
    page_token: _builtins.str
    """Token for a specific page of results, as returned from a previous list request with the same
    query parameters.
    """
    def __init__(
        self,
        *,
        parent: _builtins.str | None = ...,
        page_size: _builtins.int | None = ...,
        page_token: _builtins.str | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListKpiMappingResultsRequest: _TypeAlias = ListKpiMappingResultsRequest  # noqa: Y015

@_typing.final
class ListKpiMappingResultsResponse(_message.Message):
    """Response from ListKpiMappingResults."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    TOTAL_SIZE_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page of results, which can be sent to a subsequent list query.
    The end of the list is reached when the token is empty.
    """
    total_size: _builtins.int
    """Total number of rows, irrespective of paging."""
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.CompanyKpiMappingResults]:
        """List of results, one for each company."""

    def __init__(
        self,
        *,
        results: _abc.Iterable[_kpi_messages_pb2.CompanyKpiMappingResults] | None = ...,
        next_page_token: _builtins.str | None = ...,
        total_size: _builtins.int | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token", "results", b"results", "total_size", b"total_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListKpiMappingResultsResponse: _TypeAlias = ListKpiMappingResultsResponse  # noqa: Y015

@_typing.final
class ListCompanyBaseModelResultsRequest(_message.Message):
    """Request to ListCompanyBaseModelResults."""

    DESCRIPTOR: _descriptor.Descriptor

    PARENT_FIELD_NUMBER: _builtins.int
    PERIOD_FIELD_NUMBER: _builtins.int
    KPI_SOURCE_FIELD_NUMBER: _builtins.int
    parent: _builtins.str
    """Resource name of the company get results for."""
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def kpi_source(self) -> _kpi_messages_pb2.KpiSource.ValueType:
        """This field is no longer in use."""

    @kpi_source.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def kpi_source(self, value: _kpi_messages_pb2.KpiSource.ValueType) -> None:
        """This field is no longer in use."""

    @_builtins.property
    def period(self) -> _kpi_messages_pb2.FiscalPeriodSelector:
        """The fiscal period and frequency to get results for.
        If not specified, `RelativeFiscalPeriodSelector.CURRENT` is used and frequency is
        determined based on KPI counts. The frequency with the most number of KPIs with
        mappings for the user is used.
        """

    def __init__(
        self,
        *,
        parent: _builtins.str | None = ...,
        period: _kpi_messages_pb2.FiscalPeriodSelector | None = ...,
        kpi_source: _kpi_messages_pb2.KpiSource.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["period", b"period"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kpi_source", b"kpi_source", "parent", b"parent", "period", b"period"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyBaseModelResultsRequest: _TypeAlias = ListCompanyBaseModelResultsRequest  # noqa: Y015

@_typing.final
class ListCompanyBaseModelResultsResponse(_message.Message):
    """Response from ListCompanyBaseModelResults."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    PERIOD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.CompanyKpiModelResult]:
        """List of results."""

    @_builtins.property
    def period(self) -> _kpi_messages_pb2.FiscalPeriod:
        """Fiscal period representing the period the results are for."""

    def __init__(
        self,
        *,
        results: _abc.Iterable[_kpi_messages_pb2.CompanyKpiModelResult] | None = ...,
        period: _kpi_messages_pb2.FiscalPeriod | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["period", b"period"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["period", b"period", "results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyBaseModelResultsResponse: _TypeAlias = ListCompanyBaseModelResultsResponse  # noqa: Y015

@_typing.final
class ListCompanyHierarchicalModelResultsRequest(_message.Message):
    """Request to ListCompanyHierarchicalModelResults."""

    DESCRIPTOR: _descriptor.Descriptor

    PARENT_FIELD_NUMBER: _builtins.int
    PERIOD_FIELD_NUMBER: _builtins.int
    KPI_SOURCE_FIELD_NUMBER: _builtins.int
    parent: _builtins.str
    """Resource name of the company get results for."""
    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def kpi_source(self) -> _kpi_messages_pb2.KpiSource.ValueType:
        """This field is no longer in use."""

    @kpi_source.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def kpi_source(self, value: _kpi_messages_pb2.KpiSource.ValueType) -> None:
        """This field is no longer in use."""

    @_builtins.property
    def period(self) -> _kpi_messages_pb2.FiscalPeriodSelector:
        """The fiscal period and frequency to get results for.
        If not specified, `RelativeFiscalPeriodSelector.CURRENT` is used and frequency is
        determined based on KPI counts. The frequency with the most number of KPIs with
        mappings for the user is used.
        """

    def __init__(
        self,
        *,
        parent: _builtins.str | None = ...,
        period: _kpi_messages_pb2.FiscalPeriodSelector | None = ...,
        kpi_source: _kpi_messages_pb2.KpiSource.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["period", b"period"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kpi_source", b"kpi_source", "parent", b"parent", "period", b"period"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyHierarchicalModelResultsRequest: _TypeAlias = ListCompanyHierarchicalModelResultsRequest  # noqa: Y015

@_typing.final
class ListCompanyHierarchicalModelResultsResponse(_message.Message):
    """Response from ListCompanyHierarchicalModelResults."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    KPI_HIERARCHY_FIELD_NUMBER: _builtins.int
    PERIOD_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.CompanyKpiModelResult]:
        """List of results."""

    @_builtins.property
    def kpi_hierarchy(self) -> _kpi_messages_pb2.KpiHierarchy:
        """The KPI hierarchy for the company."""

    @_builtins.property
    def period(self) -> _kpi_messages_pb2.FiscalPeriod:
        """Fiscal period representing the period the results are for."""

    def __init__(
        self,
        *,
        results: _abc.Iterable[_kpi_messages_pb2.CompanyKpiModelResult] | None = ...,
        kpi_hierarchy: _kpi_messages_pb2.KpiHierarchy | None = ...,
        period: _kpi_messages_pb2.FiscalPeriod | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kpi_hierarchy", b"kpi_hierarchy", "period", b"period"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kpi_hierarchy", b"kpi_hierarchy", "period", b"period", "results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyHierarchicalModelResultsResponse: _TypeAlias = ListCompanyHierarchicalModelResultsResponse  # noqa: Y015

@_typing.final
class ListCompanyKpiMappingResultsRequest(_message.Message):
    """Request to ListCompanyKpiMappingResults."""

    DESCRIPTOR: _descriptor.Descriptor

    PARENT_FIELD_NUMBER: _builtins.int
    KPI_FIELD_NUMBER: _builtins.int
    parent: _builtins.str
    """Resource name of the company to get KPI mapping results for."""
    @_builtins.property
    def kpi(self) -> _kpi_messages_pb2.Kpi:
        """KPI to get KPI mapping results for.
        The fields `type`, `value` and `freq` must be specified.
        """

    def __init__(
        self,
        *,
        parent: _builtins.str | None = ...,
        kpi: _kpi_messages_pb2.Kpi | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kpi", b"kpi"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kpi", b"kpi", "parent", b"parent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyKpiMappingResultsRequest: _TypeAlias = ListCompanyKpiMappingResultsRequest  # noqa: Y015

@_typing.final
class ListCompanyKpiMappingResultsResponse(_message.Message):
    """Response from ListCompanyKpiMappingResults."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.KpiMappingResultData]:
        """KPI mapping results."""

    def __init__(
        self,
        *,
        results: _abc.Iterable[_kpi_messages_pb2.KpiMappingResultData] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyKpiMappingResultsResponse: _TypeAlias = ListCompanyKpiMappingResultsResponse  # noqa: Y015

@_typing.final
class ListCompanyKpiModelResultsRequest(_message.Message):
    """Request to ListCompanyKpiModelResults."""

    DESCRIPTOR: _descriptor.Descriptor

    PARENT_FIELD_NUMBER: _builtins.int
    KPI_FIELD_NUMBER: _builtins.int
    parent: _builtins.str
    """Resource name of the company to get model results for."""
    @_builtins.property
    def kpi(self) -> _kpi_messages_pb2.Kpi:
        """KPI to get model results for.
        The fields `type`, `value` and `freq` must be specified.
        """

    def __init__(
        self,
        *,
        parent: _builtins.str | None = ...,
        kpi: _kpi_messages_pb2.Kpi | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["kpi", b"kpi"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kpi", b"kpi", "parent", b"parent"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyKpiModelResultsRequest: _TypeAlias = ListCompanyKpiModelResultsRequest  # noqa: Y015

@_typing.final
class ListCompanyKpiModelResultsResponse(_message.Message):
    """Response from ListCompanyKpiModelResults."""

    DESCRIPTOR: _descriptor.Descriptor

    EXABEL_MODEL_FIELD_NUMBER: _builtins.int
    HIERARCHICAL_MODEL_FIELD_NUMBER: _builtins.int
    CUSTOM_MODELS_FIELD_NUMBER: _builtins.int
    KPI_MAPPING_MODELS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def exabel_model(self) -> _kpi_messages_pb2.KpiModel:
        """Exabel model."""

    @_builtins.property
    def hierarchical_model(self) -> _kpi_messages_pb2.KpiModel:
        """Hierarchical model."""

    @_builtins.property
    def custom_models(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.KpiModel]:
        """Custom models."""

    @_builtins.property
    def kpi_mapping_models(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.KpiMappingModel]:
        """Single-predictor KPI mapping models."""

    def __init__(
        self,
        *,
        exabel_model: _kpi_messages_pb2.KpiModel | None = ...,
        hierarchical_model: _kpi_messages_pb2.KpiModel | None = ...,
        custom_models: _abc.Iterable[_kpi_messages_pb2.KpiModel] | None = ...,
        kpi_mapping_models: _abc.Iterable[_kpi_messages_pb2.KpiMappingModel] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["exabel_model", b"exabel_model", "hierarchical_model", b"hierarchical_model"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["custom_models", b"custom_models", "exabel_model", b"exabel_model", "hierarchical_model", b"hierarchical_model", "kpi_mapping_models", b"kpi_mapping_models"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListCompanyKpiModelResultsResponse: _TypeAlias = ListCompanyKpiModelResultsResponse  # noqa: Y015

@_typing.final
class ListKpiScreenResultsRequest(_message.Message):
    """Request to ListKpiScreenResults."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Resource name of the KPI screen, e.g. `kpiScreens/123`."""
    page_size: _builtins.int
    """Maximum number of companies to return. Defaults to 20, and the maximum allowed value is 100."""
    page_token: _builtins.str
    """Token for a specific page of results, as returned from a previous list request with the same
    query parameters.
    """
    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
        page_size: _builtins.int | None = ...,
        page_token: _builtins.str | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "page_size", b"page_size", "page_token", b"page_token"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListKpiScreenResultsRequest: _TypeAlias = ListKpiScreenResultsRequest  # noqa: Y015

@_typing.final
class ListKpiScreenResultsResponse(_message.Message):
    """Response from ListKpiScreenResults."""

    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: _builtins.int
    TOTAL_SIZE_FIELD_NUMBER: _builtins.int
    next_page_token: _builtins.str
    """Token for the next page of results, which can be sent to a subsequent list query.
    The end of the list is reached when the token is empty.
    """
    total_size: _builtins.int
    """Total number of rows, irrespective of paging."""
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[_kpi_messages_pb2.KpiScreenCompanyResult]:
        """List of results, one for each company."""

    def __init__(
        self,
        *,
        results: _abc.Iterable[_kpi_messages_pb2.KpiScreenCompanyResult] | None = ...,
        next_page_token: _builtins.str | None = ...,
        total_size: _builtins.int | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["next_page_token", b"next_page_token", "results", b"results", "total_size", b"total_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ListKpiScreenResultsResponse: _TypeAlias = ListKpiScreenResultsResponse  # noqa: Y015
