"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2022 Exabel AS. All rights reserved."""
import builtins
import collections.abc
from ..... import exabel
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ListGroupsRequest(google.protobuf.message.Message):
    """Request to ListGroups."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___ListGroupsRequest = ListGroupsRequest

@typing_extensions.final
class ListGroupsResponse(google.protobuf.message.Message):
    """Response from ListGroups."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GROUPS_FIELD_NUMBER: builtins.int

    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[exabel.api.management.v1.user_messages_pb2.Group]:
        """List of user groups, including users in each user group."""

    def __init__(self, *, groups: collections.abc.Iterable[exabel.api.management.v1.user_messages_pb2.Group] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['groups', b'groups']) -> None:
        ...
global___ListGroupsResponse = ListGroupsResponse

@typing_extensions.final
class ListUsersRequest(google.protobuf.message.Message):
    """Request to ListUsers."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(self) -> None:
        ...
global___ListUsersRequest = ListUsersRequest

@typing_extensions.final
class ListUsersResponse(google.protobuf.message.Message):
    """Response from ListUsers."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    USERS_FIELD_NUMBER: builtins.int

    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[exabel.api.management.v1.user_messages_pb2.User]:
        """List of users."""

    def __init__(self, *, users: collections.abc.Iterable[exabel.api.management.v1.user_messages_pb2.User] | None=...) -> None:
        ...

    def ClearField(self, field_name: typing_extensions.Literal['users', b'users']) -> None:
        ...
global___ListUsersResponse = ListUsersResponse