"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from .....exabel.api.management.v1 import user_messages_pb2 as exabel_dot_api_dot_management_dot_v1_dot_user__messages__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from .....protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='exabel/api/management/v1/user_service.proto', package='exabel.api.management.v1', syntax='proto3', serialized_options=b'\n\x1ccom.exabel.api.management.v1B\x10UserServiceProtoP\x01Z\x1cexabel.com/api/management/v1', create_key=_descriptor._internal_create_key, serialized_pb=b'\n+exabel/api/management/v1/user_service.proto\x12\x18exabel.api.management.v1\x1a,exabel/api/management/v1/user_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc_gen_openapiv2/options/annotations.proto"\x13\n\x11ListGroupsRequest"E\n\x12ListGroupsResponse\x12/\n\x06groups\x18\x01 \x03(\x0b2\x1f.exabel.api.management.v1.Group"\x12\n\x10ListUsersRequest"B\n\x11ListUsersResponse\x12-\n\x05users\x18\x01 \x03(\x0b2\x1e.exabel.api.management.v1.User2\xa4\x02\n\x0bUserService\x12\x8b\x01\n\nListGroups\x12+.exabel.api.management.v1.ListGroupsRequest\x1a,.exabel.api.management.v1.ListGroupsResponse""\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/groups\x92A\r\x12\x0bList groups\x12\x86\x01\n\tListUsers\x12*.exabel.api.management.v1.ListUsersRequest\x1a+.exabel.api.management.v1.ListUsersResponse" \x82\xd3\xe4\x93\x02\x0b\x12\t/v1/users\x92A\x0c\x12\nList usersBP\n\x1ccom.exabel.api.management.v1B\x10UserServiceProtoP\x01Z\x1cexabel.com/api/management/v1b\x06proto3', dependencies=[exabel_dot_api_dot_management_dot_v1_dot_user__messages__pb2.DESCRIPTOR, google_dot_api_dot_annotations__pb2.DESCRIPTOR, google_dot_api_dot_field__behavior__pb2.DESCRIPTOR, google_dot_protobuf_dot_empty__pb2.DESCRIPTOR, protoc__gen__openapiv2_dot_options_dot_annotations__pb2.DESCRIPTOR])
_LISTGROUPSREQUEST = _descriptor.Descriptor(name='ListGroupsRequest', full_name='exabel.api.management.v1.ListGroupsRequest', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=259, serialized_end=278)
_LISTGROUPSRESPONSE = _descriptor.Descriptor(name='ListGroupsResponse', full_name='exabel.api.management.v1.ListGroupsResponse', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='groups', full_name='exabel.api.management.v1.ListGroupsResponse.groups', index=0, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=280, serialized_end=349)
_LISTUSERSREQUEST = _descriptor.Descriptor(name='ListUsersRequest', full_name='exabel.api.management.v1.ListUsersRequest', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=351, serialized_end=369)
_LISTUSERSRESPONSE = _descriptor.Descriptor(name='ListUsersResponse', full_name='exabel.api.management.v1.ListUsersResponse', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='users', full_name='exabel.api.management.v1.ListUsersResponse.users', index=0, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=371, serialized_end=437)
_LISTGROUPSRESPONSE.fields_by_name['groups'].message_type = exabel_dot_api_dot_management_dot_v1_dot_user__messages__pb2._GROUP
_LISTUSERSRESPONSE.fields_by_name['users'].message_type = exabel_dot_api_dot_management_dot_v1_dot_user__messages__pb2._USER
DESCRIPTOR.message_types_by_name['ListGroupsRequest'] = _LISTGROUPSREQUEST
DESCRIPTOR.message_types_by_name['ListGroupsResponse'] = _LISTGROUPSRESPONSE
DESCRIPTOR.message_types_by_name['ListUsersRequest'] = _LISTUSERSREQUEST
DESCRIPTOR.message_types_by_name['ListUsersResponse'] = _LISTUSERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
ListGroupsRequest = _reflection.GeneratedProtocolMessageType('ListGroupsRequest', (_message.Message,), {'DESCRIPTOR': _LISTGROUPSREQUEST, '__module__': 'exabel.api.management.v1.user_service_pb2'})
_sym_db.RegisterMessage(ListGroupsRequest)
ListGroupsResponse = _reflection.GeneratedProtocolMessageType('ListGroupsResponse', (_message.Message,), {'DESCRIPTOR': _LISTGROUPSRESPONSE, '__module__': 'exabel.api.management.v1.user_service_pb2'})
_sym_db.RegisterMessage(ListGroupsResponse)
ListUsersRequest = _reflection.GeneratedProtocolMessageType('ListUsersRequest', (_message.Message,), {'DESCRIPTOR': _LISTUSERSREQUEST, '__module__': 'exabel.api.management.v1.user_service_pb2'})
_sym_db.RegisterMessage(ListUsersRequest)
ListUsersResponse = _reflection.GeneratedProtocolMessageType('ListUsersResponse', (_message.Message,), {'DESCRIPTOR': _LISTUSERSRESPONSE, '__module__': 'exabel.api.management.v1.user_service_pb2'})
_sym_db.RegisterMessage(ListUsersResponse)
DESCRIPTOR._options = None
_USERSERVICE = _descriptor.ServiceDescriptor(name='UserService', full_name='exabel.api.management.v1.UserService', file=DESCRIPTOR, index=0, serialized_options=None, create_key=_descriptor._internal_create_key, serialized_start=440, serialized_end=732, methods=[_descriptor.MethodDescriptor(name='ListGroups', full_name='exabel.api.management.v1.UserService.ListGroups', index=0, containing_service=None, input_type=_LISTGROUPSREQUEST, output_type=_LISTGROUPSRESPONSE, serialized_options=b'\x82\xd3\xe4\x93\x02\x0c\x12\n/v1/groups\x92A\r\x12\x0bList groups', create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='ListUsers', full_name='exabel.api.management.v1.UserService.ListUsers', index=1, containing_service=None, input_type=_LISTUSERSREQUEST, output_type=_LISTUSERSRESPONSE, serialized_options=b'\x82\xd3\xe4\x93\x02\x0b\x12\t/v1/users\x92A\x0c\x12\nList users', create_key=_descriptor._internal_create_key)])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)
DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE