"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from .....exabel.api.analytics.v1 import derived_signal_messages_pb2 as exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2
from .....protoc_gen_openapiv2.options import annotations_pb2 as protoc__gen__openapiv2_dot_options_dot_annotations__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='exabel/api/analytics/v1/derived_signal_service.proto', package='exabel.api.analytics.v1', syntax='proto3', serialized_options=b'\n\x1bcom.exabel.api.analytics.v1B\x19DerivedSignalServiceProtoP\x01Z\x1bexabel.com/api/analytics/v1', create_key=_descriptor._internal_create_key, serialized_pb=b'\n4exabel/api/analytics/v1/derived_signal_service.proto\x12\x17exabel.api.analytics.v1\x1a5exabel/api/analytics/v1/derived_signal_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a.protoc_gen_openapiv2/options/annotations.proto"F\n\x17GetDerivedSignalRequest\x12+\n\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\x92A\x17\xca>\x14\xfa\x02\x11derivedSignalName"i\n\x1aCreateDerivedSignalRequest\x12;\n\x06signal\x18\x01 \x01(\x0b2&.exabel.api.analytics.v1.DerivedSignalB\x03\xe0A\x02\x12\x0e\n\x06folder\x18\x02 \x01(\t"\x8a\x01\n\x1aUpdateDerivedSignalRequest\x12;\n\x06signal\x18\x01 \x01(\x0b2&.exabel.api.analytics.v1.DerivedSignalB\x03\xe0A\x02\x12/\n\x0bupdate_mask\x18\x02 \x01(\x0b2\x1a.google.protobuf.FieldMask"I\n\x1aDeleteDerivedSignalRequest\x12+\n\x04name\x18\x01 \x01(\tB\x1d\xe0A\x02\x92A\x17\xca>\x14\xfa\x02\x11derivedSignalName2\xdb\x05\n\x14DerivedSignalService\x12\xa8\x01\n\x10GetDerivedSignal\x120.exabel.api.analytics.v1.GetDerivedSignalRequest\x1a&.exabel.api.analytics.v1.DerivedSignal":\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/{name=derivedSignals/*}\x92A\x14\x12\x12Get derived signal\x12\xb0\x01\n\x13CreateDerivedSignal\x123.exabel.api.analytics.v1.CreateDerivedSignalRequest\x1a&.exabel.api.analytics.v1.DerivedSignal"<\x82\xd3\xe4\x93\x02\x1c"\x12/v1/derivedSignals:\x06signal\x92A\x17\x12\x15Create derived signal\x12\xc0\x01\n\x13UpdateDerivedSignal\x123.exabel.api.analytics.v1.UpdateDerivedSignalRequest\x1a&.exabel.api.analytics.v1.DerivedSignal"L\x82\xd3\xe4\x93\x02,2"/v1/{signal.name=derivedSignals/*}:\x06signal\x92A\x17\x12\x15Update derived signal\x12\xa1\x01\n\x13DeleteDerivedSignal\x123.exabel.api.analytics.v1.DeleteDerivedSignalRequest\x1a\x16.google.protobuf.Empty"=\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/{name=derivedSignals/*}\x92A\x17\x12\x15Delete derived signalBW\n\x1bcom.exabel.api.analytics.v1B\x19DerivedSignalServiceProtoP\x01Z\x1bexabel.com/api/analytics/v1b\x06proto3', dependencies=[exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2.DESCRIPTOR, google_dot_api_dot_annotations__pb2.DESCRIPTOR, google_dot_api_dot_field__behavior__pb2.DESCRIPTOR, google_dot_protobuf_dot_empty__pb2.DESCRIPTOR, google_dot_protobuf_dot_field__mask__pb2.DESCRIPTOR, protoc__gen__openapiv2_dot_options_dot_annotations__pb2.DESCRIPTOR])
_GETDERIVEDSIGNALREQUEST = _descriptor.Descriptor(name='GetDerivedSignalRequest', full_name='exabel.api.analytics.v1.GetDerivedSignalRequest', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='name', full_name='exabel.api.analytics.v1.GetDerivedSignalRequest.name', index=0, number=1, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=b'\xe0A\x02\x92A\x17\xca>\x14\xfa\x02\x11derivedSignalName', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=310, serialized_end=380)
_CREATEDERIVEDSIGNALREQUEST = _descriptor.Descriptor(name='CreateDerivedSignalRequest', full_name='exabel.api.analytics.v1.CreateDerivedSignalRequest', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='signal', full_name='exabel.api.analytics.v1.CreateDerivedSignalRequest.signal', index=0, number=1, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=b'\xe0A\x02', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='folder', full_name='exabel.api.analytics.v1.CreateDerivedSignalRequest.folder', index=1, number=2, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=382, serialized_end=487)
_UPDATEDERIVEDSIGNALREQUEST = _descriptor.Descriptor(name='UpdateDerivedSignalRequest', full_name='exabel.api.analytics.v1.UpdateDerivedSignalRequest', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='signal', full_name='exabel.api.analytics.v1.UpdateDerivedSignalRequest.signal', index=0, number=1, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=b'\xe0A\x02', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='update_mask', full_name='exabel.api.analytics.v1.UpdateDerivedSignalRequest.update_mask', index=1, number=2, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=490, serialized_end=628)
_DELETEDERIVEDSIGNALREQUEST = _descriptor.Descriptor(name='DeleteDerivedSignalRequest', full_name='exabel.api.analytics.v1.DeleteDerivedSignalRequest', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='name', full_name='exabel.api.analytics.v1.DeleteDerivedSignalRequest.name', index=0, number=1, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=b'\xe0A\x02\x92A\x17\xca>\x14\xfa\x02\x11derivedSignalName', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=630, serialized_end=703)
_CREATEDERIVEDSIGNALREQUEST.fields_by_name['signal'].message_type = exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2._DERIVEDSIGNAL
_UPDATEDERIVEDSIGNALREQUEST.fields_by_name['signal'].message_type = exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2._DERIVEDSIGNAL
_UPDATEDERIVEDSIGNALREQUEST.fields_by_name['update_mask'].message_type = google_dot_protobuf_dot_field__mask__pb2._FIELDMASK
DESCRIPTOR.message_types_by_name['GetDerivedSignalRequest'] = _GETDERIVEDSIGNALREQUEST
DESCRIPTOR.message_types_by_name['CreateDerivedSignalRequest'] = _CREATEDERIVEDSIGNALREQUEST
DESCRIPTOR.message_types_by_name['UpdateDerivedSignalRequest'] = _UPDATEDERIVEDSIGNALREQUEST
DESCRIPTOR.message_types_by_name['DeleteDerivedSignalRequest'] = _DELETEDERIVEDSIGNALREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
GetDerivedSignalRequest = _reflection.GeneratedProtocolMessageType('GetDerivedSignalRequest', (_message.Message,), {'DESCRIPTOR': _GETDERIVEDSIGNALREQUEST, '__module__': 'exabel.api.analytics.v1.derived_signal_service_pb2'})
_sym_db.RegisterMessage(GetDerivedSignalRequest)
CreateDerivedSignalRequest = _reflection.GeneratedProtocolMessageType('CreateDerivedSignalRequest', (_message.Message,), {'DESCRIPTOR': _CREATEDERIVEDSIGNALREQUEST, '__module__': 'exabel.api.analytics.v1.derived_signal_service_pb2'})
_sym_db.RegisterMessage(CreateDerivedSignalRequest)
UpdateDerivedSignalRequest = _reflection.GeneratedProtocolMessageType('UpdateDerivedSignalRequest', (_message.Message,), {'DESCRIPTOR': _UPDATEDERIVEDSIGNALREQUEST, '__module__': 'exabel.api.analytics.v1.derived_signal_service_pb2'})
_sym_db.RegisterMessage(UpdateDerivedSignalRequest)
DeleteDerivedSignalRequest = _reflection.GeneratedProtocolMessageType('DeleteDerivedSignalRequest', (_message.Message,), {'DESCRIPTOR': _DELETEDERIVEDSIGNALREQUEST, '__module__': 'exabel.api.analytics.v1.derived_signal_service_pb2'})
_sym_db.RegisterMessage(DeleteDerivedSignalRequest)
DESCRIPTOR._options = None
_GETDERIVEDSIGNALREQUEST.fields_by_name['name']._options = None
_CREATEDERIVEDSIGNALREQUEST.fields_by_name['signal']._options = None
_UPDATEDERIVEDSIGNALREQUEST.fields_by_name['signal']._options = None
_DELETEDERIVEDSIGNALREQUEST.fields_by_name['name']._options = None
_DERIVEDSIGNALSERVICE = _descriptor.ServiceDescriptor(name='DerivedSignalService', full_name='exabel.api.analytics.v1.DerivedSignalService', file=DESCRIPTOR, index=0, serialized_options=None, create_key=_descriptor._internal_create_key, serialized_start=706, serialized_end=1437, methods=[_descriptor.MethodDescriptor(name='GetDerivedSignal', full_name='exabel.api.analytics.v1.DerivedSignalService.GetDerivedSignal', index=0, containing_service=None, input_type=_GETDERIVEDSIGNALREQUEST, output_type=exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2._DERIVEDSIGNAL, serialized_options=b'\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/{name=derivedSignals/*}\x92A\x14\x12\x12Get derived signal', create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='CreateDerivedSignal', full_name='exabel.api.analytics.v1.DerivedSignalService.CreateDerivedSignal', index=1, containing_service=None, input_type=_CREATEDERIVEDSIGNALREQUEST, output_type=exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2._DERIVEDSIGNAL, serialized_options=b'\x82\xd3\xe4\x93\x02\x1c"\x12/v1/derivedSignals:\x06signal\x92A\x17\x12\x15Create derived signal', create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='UpdateDerivedSignal', full_name='exabel.api.analytics.v1.DerivedSignalService.UpdateDerivedSignal', index=2, containing_service=None, input_type=_UPDATEDERIVEDSIGNALREQUEST, output_type=exabel_dot_api_dot_analytics_dot_v1_dot_derived__signal__messages__pb2._DERIVEDSIGNAL, serialized_options=b'\x82\xd3\xe4\x93\x02,2"/v1/{signal.name=derivedSignals/*}:\x06signal\x92A\x17\x12\x15Update derived signal', create_key=_descriptor._internal_create_key), _descriptor.MethodDescriptor(name='DeleteDerivedSignal', full_name='exabel.api.analytics.v1.DerivedSignalService.DeleteDerivedSignal', index=3, containing_service=None, input_type=_DELETEDERIVEDSIGNALREQUEST, output_type=google_dot_protobuf_dot_empty__pb2._EMPTY, serialized_options=b'\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/{name=derivedSignals/*}\x92A\x17\x12\x15Delete derived signal', create_key=_descriptor._internal_create_key)])
_sym_db.RegisterServiceDescriptor(_DERIVEDSIGNALSERVICE)
DESCRIPTOR.services_by_name['DerivedSignalService'] = _DERIVEDSIGNALSERVICE