"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='exabel/api/analytics/v1/derived_signal_messages.proto', package='exabel.api.analytics.v1', syntax='proto3', serialized_options=b'\n\x1bcom.exabel.api.analytics.v1B\x1aDerivedSignalMessagesProtoP\x01Z\x1bexabel.com/api/analytics/v1', create_key=_descriptor._internal_create_key, serialized_pb=b'\n5exabel/api/analytics/v1/derived_signal_messages.proto\x12\x17exabel.api.analytics.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/wrappers.proto"\x97\x01\n\rDerivedSignal\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x12\n\nexpression\x18\x03 \x01(\t\x12\x13\n\x0bdescription\x18\x04 \x01(\t\x12@\n\x08metadata\x18\x05 \x01(\x0b2..exabel.api.analytics.v1.DerivedSignalMetadata"\xbf\x01\n\x15DerivedSignalMetadata\x12-\n\x08decimals\x18\x01 \x01(\x0b2\x1b.google.protobuf.Int32Value\x128\n\x04unit\x18\x02 \x01(\x0e2*.exabel.api.analytics.v1.DerivedSignalUnit\x12=\n\x04type\x18\x03 \x01(\x0e2*.exabel.api.analytics.v1.DerivedSignalTypeB\x03\xe0A\x03*a\n\x11DerivedSignalUnit\x12\x1f\n\x1bDERIVED_SIGNAL_UNIT_INVALID\x10\x00\x12\n\n\x06NUMBER\x10\x01\x12\t\n\x05RATIO\x10\x02\x12\x14\n\x10RATIO_DIFFERENCE\x10\x03*\x9a\x01\n\x11DerivedSignalType\x12\x1f\n\x1bDERIVED_SIGNAL_TYPE_INVALID\x10\x00\x12\x12\n\x0eDERIVED_SIGNAL\x10\x01\x12\x18\n\x14FILE_UPLOADED_SIGNAL\x10\x02\x12 \n\x1cFILE_UPLOADED_COMPANY_SIGNAL\x10\x03\x12\x14\n\x10PERSISTED_SIGNAL\x10\x04BX\n\x1bcom.exabel.api.analytics.v1B\x1aDerivedSignalMessagesProtoP\x01Z\x1bexabel.com/api/analytics/v1b\x06proto3', dependencies=[google_dot_api_dot_field__behavior__pb2.DESCRIPTOR, google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR])
_DERIVEDSIGNALUNIT = _descriptor.EnumDescriptor(name='DerivedSignalUnit', full_name='exabel.api.analytics.v1.DerivedSignalUnit', filename=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key, values=[_descriptor.EnumValueDescriptor(name='DERIVED_SIGNAL_UNIT_INVALID', index=0, number=0, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='NUMBER', index=1, number=1, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='RATIO', index=2, number=2, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='RATIO_DIFFERENCE', index=3, number=3, serialized_options=None, type=None, create_key=_descriptor._internal_create_key)], containing_type=None, serialized_options=None, serialized_start=495, serialized_end=592)
_sym_db.RegisterEnumDescriptor(_DERIVEDSIGNALUNIT)
DerivedSignalUnit = enum_type_wrapper.EnumTypeWrapper(_DERIVEDSIGNALUNIT)
_DERIVEDSIGNALTYPE = _descriptor.EnumDescriptor(name='DerivedSignalType', full_name='exabel.api.analytics.v1.DerivedSignalType', filename=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key, values=[_descriptor.EnumValueDescriptor(name='DERIVED_SIGNAL_TYPE_INVALID', index=0, number=0, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='DERIVED_SIGNAL', index=1, number=1, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='FILE_UPLOADED_SIGNAL', index=2, number=2, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='FILE_UPLOADED_COMPANY_SIGNAL', index=3, number=3, serialized_options=None, type=None, create_key=_descriptor._internal_create_key), _descriptor.EnumValueDescriptor(name='PERSISTED_SIGNAL', index=4, number=4, serialized_options=None, type=None, create_key=_descriptor._internal_create_key)], containing_type=None, serialized_options=None, serialized_start=595, serialized_end=749)
_sym_db.RegisterEnumDescriptor(_DERIVEDSIGNALTYPE)
DerivedSignalType = enum_type_wrapper.EnumTypeWrapper(_DERIVEDSIGNALTYPE)
DERIVED_SIGNAL_UNIT_INVALID = 0
NUMBER = 1
RATIO = 2
RATIO_DIFFERENCE = 3
DERIVED_SIGNAL_TYPE_INVALID = 0
DERIVED_SIGNAL = 1
FILE_UPLOADED_SIGNAL = 2
FILE_UPLOADED_COMPANY_SIGNAL = 3
PERSISTED_SIGNAL = 4
_DERIVEDSIGNAL = _descriptor.Descriptor(name='DerivedSignal', full_name='exabel.api.analytics.v1.DerivedSignal', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='name', full_name='exabel.api.analytics.v1.DerivedSignal.name', index=0, number=1, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='label', full_name='exabel.api.analytics.v1.DerivedSignal.label', index=1, number=2, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='expression', full_name='exabel.api.analytics.v1.DerivedSignal.expression', index=2, number=3, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='description', full_name='exabel.api.analytics.v1.DerivedSignal.description', index=3, number=4, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='metadata', full_name='exabel.api.analytics.v1.DerivedSignal.metadata', index=4, number=5, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=148, serialized_end=299)
_DERIVEDSIGNALMETADATA = _descriptor.Descriptor(name='DerivedSignalMetadata', full_name='exabel.api.analytics.v1.DerivedSignalMetadata', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='decimals', full_name='exabel.api.analytics.v1.DerivedSignalMetadata.decimals', index=0, number=1, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='unit', full_name='exabel.api.analytics.v1.DerivedSignalMetadata.unit', index=1, number=2, type=14, cpp_type=8, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='type', full_name='exabel.api.analytics.v1.DerivedSignalMetadata.type', index=2, number=3, type=14, cpp_type=8, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=b'\xe0A\x03', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=302, serialized_end=493)
_DERIVEDSIGNAL.fields_by_name['metadata'].message_type = _DERIVEDSIGNALMETADATA
_DERIVEDSIGNALMETADATA.fields_by_name['decimals'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_DERIVEDSIGNALMETADATA.fields_by_name['unit'].enum_type = _DERIVEDSIGNALUNIT
_DERIVEDSIGNALMETADATA.fields_by_name['type'].enum_type = _DERIVEDSIGNALTYPE
DESCRIPTOR.message_types_by_name['DerivedSignal'] = _DERIVEDSIGNAL
DESCRIPTOR.message_types_by_name['DerivedSignalMetadata'] = _DERIVEDSIGNALMETADATA
DESCRIPTOR.enum_types_by_name['DerivedSignalUnit'] = _DERIVEDSIGNALUNIT
DESCRIPTOR.enum_types_by_name['DerivedSignalType'] = _DERIVEDSIGNALTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
DerivedSignal = _reflection.GeneratedProtocolMessageType('DerivedSignal', (_message.Message,), {'DESCRIPTOR': _DERIVEDSIGNAL, '__module__': 'exabel.api.analytics.v1.derived_signal_messages_pb2'})
_sym_db.RegisterMessage(DerivedSignal)
DerivedSignalMetadata = _reflection.GeneratedProtocolMessageType('DerivedSignalMetadata', (_message.Message,), {'DESCRIPTOR': _DERIVEDSIGNALMETADATA, '__module__': 'exabel.api.analytics.v1.derived_signal_messages_pb2'})
_sym_db.RegisterMessage(DerivedSignalMetadata)
DESCRIPTOR._options = None
_DERIVEDSIGNALMETADATA.fields_by_name['type']._options = None