"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2025 Exabel AS. All rights reserved."""
import builtins
import collections.abc
from ..... import exabel
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateKpiMappingGroupRequest(google.protobuf.message.Message):
    """Request message to CreateKpiMappingGroup."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    KPI_MAPPING_GROUP_FIELD_NUMBER: builtins.int
    parent: builtins.str
    'Resource name of the Kpi mapping which the group should be added to.'

    @property
    def kpi_mapping_group(self) -> exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroup:
        """KpiMappingGroup to create. The name field in the Kpi mapping group is ignored and may be left empty."""

    def __init__(self, *, parent: builtins.str | None=..., kpi_mapping_group: exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroup | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['kpi_mapping_group', b'kpi_mapping_group']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['kpi_mapping_group', b'kpi_mapping_group', 'parent', b'parent']) -> None:
        ...
global___CreateKpiMappingGroupRequest = CreateKpiMappingGroupRequest

@typing.final
class GetKpiMappingGroupRequest(google.protobuf.message.Message):
    """Request message to GetKpiMappingGroup."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Resource name of Kpi mapping group to retrieve.'

    def __init__(self, *, name: builtins.str | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['name', b'name']) -> None:
        ...
global___GetKpiMappingGroupRequest = GetKpiMappingGroupRequest

@typing.final
class ListKpiMappingGroupsRequest(google.protobuf.message.Message):
    """Request message to ListKpiMappingGroups."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    PARENT_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    COMPANIES_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    SKIP_FIELD_NUMBER: builtins.int
    parent: builtins.str
    'Resource name of Kpi mapping to list groups for.'
    type: exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroupType.ValueType
    'KPI mapping group types to list.'
    page_size: builtins.int
    'The page size. Default is 100 and max is 1000.'
    page_token: builtins.str
    'A page token, received from the previous call to list Kpi mapping groups.'
    skip: builtins.int
    'Number of KPI mapping groups to skip relative to page_token. Negative value is allowed.\n    Skipping past end of list will return no groups.\n    Skipping past start of list will return groups from start of list.\n    '

    @property
    def companies(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Companies to retrieve groups for. If no companies are specified, results for all companies are
        returned. Only supported for type=COMPANY_SPECIFIC.
        Example: `"entityTypes/company/entities/F_67890-E"`.
        """

    def __init__(self, *, parent: builtins.str | None=..., type: exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroupType.ValueType | None=..., companies: collections.abc.Iterable[builtins.str] | None=..., page_size: builtins.int | None=..., page_token: builtins.str | None=..., skip: builtins.int | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['companies', b'companies', 'page_size', b'page_size', 'page_token', b'page_token', 'parent', b'parent', 'skip', b'skip', 'type', b'type']) -> None:
        ...
global___ListKpiMappingGroupsRequest = ListKpiMappingGroupsRequest

@typing.final
class ListKpiMappingGroupsResponse(google.protobuf.message.Message):
    """Response message to ListKpiMappingGroups."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GROUPS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    TOTAL_SIZE_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    'Token for the next page of results, which can be sent to a subsequent query.\n    The end of the list is reached when the token is empty.\n    '
    total_size: builtins.int
    'Total number of KPI mapping groups for this request.'

    @property
    def groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroup]:
        """List of KPI mappings groups."""

    def __init__(self, *, groups: collections.abc.Iterable[exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroup] | None=..., next_page_token: builtins.str | None=..., total_size: builtins.int | None=...) -> None:
        ...

    def ClearField(self, field_name: typing.Literal['groups', b'groups', 'next_page_token', b'next_page_token', 'total_size', b'total_size']) -> None:
        ...
global___ListKpiMappingGroupsResponse = ListKpiMappingGroupsResponse

@typing.final
class UpdateKpiMappingGroupRequest(google.protobuf.message.Message):
    """Request message to UpdateKpiMappingGroup."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KPI_MAPPING_GROUP_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int

    @property
    def kpi_mapping_group(self) -> exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroup:
        """KpiMappingGroup to update."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Use this to update only selected fields. For example, specify `display_name` to update only
        the display name.

        For REST requests, this is a comma-separated string.
        """

    def __init__(self, *, kpi_mapping_group: exabel.api.analytics.v1.kpi_mapping_messages_pb2.KpiMappingGroup | None=..., update_mask: google.protobuf.field_mask_pb2.FieldMask | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['kpi_mapping_group', b'kpi_mapping_group', 'update_mask', b'update_mask']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['kpi_mapping_group', b'kpi_mapping_group', 'update_mask', b'update_mask']) -> None:
        ...
global___UpdateKpiMappingGroupRequest = UpdateKpiMappingGroupRequest