"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2025 Exabel AS. All rights reserved."""
import builtins
from ..... import exabel
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing
if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _KpiMappingGroupType:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _KpiMappingGroupTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_KpiMappingGroupType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    KPI_MAPPING_GROUP_TYPE_UNSPECIFIED: _KpiMappingGroupType.ValueType
    'Unspecified.'
    BULK: _KpiMappingGroupType.ValueType
    'Bulk mapping groups.'
    COMPANY_SPECIFIC: _KpiMappingGroupType.ValueType
    'Company specific mapping groups.'

class KpiMappingGroupType(_KpiMappingGroupType, metaclass=_KpiMappingGroupTypeEnumTypeWrapper):
    """Specifies KPI mapping group types."""
KPI_MAPPING_GROUP_TYPE_UNSPECIFIED: KpiMappingGroupType.ValueType
'Unspecified.'
BULK: KpiMappingGroupType.ValueType
'Bulk mapping groups.'
COMPANY_SPECIFIC: KpiMappingGroupType.ValueType
'Company specific mapping groups.'
global___KpiMappingGroupType = KpiMappingGroupType

class _ResampleMethod:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ResampleMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResampleMethod.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESAMPLE_METHOD_UNSPECIFIED: _ResampleMethod.ValueType
    'Unspecified.'
    NO_RESAMPLE: _ResampleMethod.ValueType
    'No resampling.'
    RESAMPLE_MEAN: _ResampleMethod.ValueType
    'Mean.'
    RESAMPLE_SUM: _ResampleMethod.ValueType
    'Sum.'
    RESAMPLE_MEDIAN: _ResampleMethod.ValueType
    'Median.'
    RESAMPLE_MEAN_TIMES_DAYS: _ResampleMethod.ValueType
    'Mean times days.'
    RESAMPLE_LAST: _ResampleMethod.ValueType
    'Last.'

class ResampleMethod(_ResampleMethod, metaclass=_ResampleMethodEnumTypeWrapper):
    """Specifies how to resample a signal."""
RESAMPLE_METHOD_UNSPECIFIED: ResampleMethod.ValueType
'Unspecified.'
NO_RESAMPLE: ResampleMethod.ValueType
'No resampling.'
RESAMPLE_MEAN: ResampleMethod.ValueType
'Mean.'
RESAMPLE_SUM: ResampleMethod.ValueType
'Sum.'
RESAMPLE_MEDIAN: ResampleMethod.ValueType
'Median.'
RESAMPLE_MEAN_TIMES_DAYS: ResampleMethod.ValueType
'Mean times days.'
RESAMPLE_LAST: ResampleMethod.ValueType
'Last.'
global___ResampleMethod = ResampleMethod

@typing.final
class KpiMappingGroup(google.protobuf.message.Message):
    """A KPI mapping group."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    KPI_FIELD_NUMBER: builtins.int
    PROXY_SIGNAL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    ENTITY_SET_FIELD_NUMBER: builtins.int
    PROXY_RESAMPLE_METHOD_FIELD_NUMBER: builtins.int
    name: builtins.str
    'Resource name. E.g "kpiMappings/123/groups/4".'
    display_name: builtins.str
    'Display name.'
    type: global___KpiMappingGroupType.ValueType
    'Type of KPI mapping group.'
    proxy_resample_method: global___ResampleMethod.ValueType
    'Specifies how to resample the proxy signal.'

    @property
    def kpi(self) -> exabel.api.analytics.v1.kpi_messages_pb2.Kpi:
        """The KPI for the group."""

    @property
    def proxy_signal(self) -> exabel.api.analytics.v1.derived_signal_messages_pb2.DerivedSignal:
        """Proxy signal."""

    @property
    def entity_set(self) -> exabel.api.analytics.v1.common_messages_pb2.EntitySet:
        """The entities for which this group defines KPI mappings.
        All the entities must be companies.
        """

    def __init__(self, *, name: builtins.str | None=..., display_name: builtins.str | None=..., kpi: exabel.api.analytics.v1.kpi_messages_pb2.Kpi | None=..., proxy_signal: exabel.api.analytics.v1.derived_signal_messages_pb2.DerivedSignal | None=..., type: global___KpiMappingGroupType.ValueType | None=..., entity_set: exabel.api.analytics.v1.common_messages_pb2.EntitySet | None=..., proxy_resample_method: global___ResampleMethod.ValueType | None=...) -> None:
        ...

    def HasField(self, field_name: typing.Literal['entity_set', b'entity_set', 'kpi', b'kpi', 'proxy_signal', b'proxy_signal']) -> builtins.bool:
        ...

    def ClearField(self, field_name: typing.Literal['display_name', b'display_name', 'entity_set', b'entity_set', 'kpi', b'kpi', 'name', b'name', 'proxy_resample_method', b'proxy_resample_method', 'proxy_signal', b'proxy_signal', 'type', b'type']) -> None:
        ...
global___KpiMappingGroup = KpiMappingGroup