"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2019-2024 Exabel AS. All rights reserved."""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Aggregation:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AggregationEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Aggregation.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AGGREGATION_INVALID: _Aggregation.ValueType  # 0
    """Aggregation is unspecified and invalid. Aggregation must be set."""
    MEAN: _Aggregation.ValueType  # 1
    """Takes the arithmetic mean of the data values. Example: 2, 1, 3, 5, 4 -> 3."""
    FIRST: _Aggregation.ValueType  # 2
    """Selects the first value. Example: 2, 1, 3, 5, 4 -> 2."""
    LAST: _Aggregation.ValueType  # 3
    """Selects the last value. Example: 2, 1, 3, 5, 4 -> 4."""
    SUM: _Aggregation.ValueType  # 4
    """Sums the data values. Example: 2, 1, 3, 5, 4 -> 15."""
    MIN: _Aggregation.ValueType  # 5
    """Selects the minimum value. Example: 2, 1, 3, 5, 4 -> 1."""
    MAX: _Aggregation.ValueType  # 6
    """Selects the maximum value. Example: 2, 1, 3, 5, 4 -> 5."""
    MEDIAN: _Aggregation.ValueType  # 7
    """Selects the median value. Example: 2, 1, 3, 5, 1000 -> 3."""

class Aggregation(_Aggregation, metaclass=_AggregationEnumTypeWrapper):
    """Aggregation methods."""

AGGREGATION_INVALID: Aggregation.ValueType  # 0
"""Aggregation is unspecified and invalid. Aggregation must be set."""
MEAN: Aggregation.ValueType  # 1
"""Takes the arithmetic mean of the data values. Example: 2, 1, 3, 5, 4 -> 3."""
FIRST: Aggregation.ValueType  # 2
"""Selects the first value. Example: 2, 1, 3, 5, 4 -> 2."""
LAST: Aggregation.ValueType  # 3
"""Selects the last value. Example: 2, 1, 3, 5, 4 -> 4."""
SUM: Aggregation.ValueType  # 4
"""Sums the data values. Example: 2, 1, 3, 5, 4 -> 15."""
MIN: Aggregation.ValueType  # 5
"""Selects the minimum value. Example: 2, 1, 3, 5, 4 -> 1."""
MAX: Aggregation.ValueType  # 6
"""Selects the maximum value. Example: 2, 1, 3, 5, 4 -> 5."""
MEDIAN: Aggregation.ValueType  # 7
"""Selects the median value. Example: 2, 1, 3, 5, 1000 -> 3."""
Global___Aggregation: _TypeAlias = Aggregation  # noqa: Y015
