"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright (c) 2024 Exabel AS. All rights reserved."""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Change:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ChangeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Change.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CHANGE_UNSPECIFIED: _Change.ValueType  # 0
    """Change is unspecified and invalid."""
    RELATIVE: _Change.ValueType  # 1
    """Change should be calculated relative to the previous value. (Default.)"""
    ABSOLUTE: _Change.ValueType  # 2
    """Change should be calculated in absolute terms to the previous value."""

class Change(_Change, metaclass=_ChangeEnumTypeWrapper):
    """Defines the possible methods to calculate change."""

CHANGE_UNSPECIFIED: Change.ValueType  # 0
"""Change is unspecified and invalid."""
RELATIVE: Change.ValueType  # 1
"""Change should be calculated relative to the previous value. (Default.)"""
ABSOLUTE: Change.ValueType  # 2
"""Change should be calculated in absolute terms to the previous value."""
Global___Change: _TypeAlias = Change  # noqa: Y015
