# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exabel/api/math/change.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'exabel/api/math/change.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x65xabel/api/math/change.proto\x12\x0f\x65xabel.api.math*<\n\x06\x43hange\x12\x16\n\x12\x43HANGE_UNSPECIFIED\x10\x00\x12\x0c\n\x08RELATIVE\x10\x01\x12\x0c\n\x08\x41\x42SOLUTE\x10\x02\x42\x39\n\x13\x63om.exabel.api.mathB\x0b\x43hangeProtoP\x01Z\x13\x65xabel.com/api/mathb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exabel.api.math.change_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.exabel.api.mathB\013ChangeProtoP\001Z\023exabel.com/api/math'
  _globals['_CHANGE']._serialized_start=49
  _globals['_CHANGE']._serialized_end=109
# @@protoc_insertion_point(module_scope)
