name: Builds and tests the Python Package on pull requests

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        pip install pipenv wheel
        pipenv sync --system

    - name: Test package
      run: ./tests.sh

    - name: Build package
      run: ./build.sh

    - name: Cache build
      uses: actions/cache@v4
      with:
        path: ./dist
        key: build-cache-${{ github.sha }}

  test-install:
    needs: build-package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: true

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Recover cache
      uses: actions/cache@v4
      with:
        path: ./dist
        key: build-cache-${{ github.sha }}

    - name: Install SDK from cache
      run: |
        PACKAGE=$(ls ./dist/ | grep -P .+\.whl$)
        pip install ./dist/$PACKAGE --no-cache-dir

