name: Build, test and publish Python Package

on:
  release:
    types: [published]
    branches: [main]
  workflow_dispatch:

jobs:
  validate-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Check git tag against package version
      run: ./check_package_version.sh

  build-and-test:
    needs: validate-version
    uses: ./.github/workflows/build_test.yml
    with:
      cache-key: 'build-cache'

  publish-package-to-pypi:
    if: always()
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    steps:
    - name: Recover cache
      if: needs.build-and-test.result == 'success'
      uses: actions/cache@v5
      with:
        path: ./dist
        key: build-cache

    - name: Publish package to PyPI
      if: needs.build-and-test.result == 'success'
      uses: pypa/gh-action-pypi-publish@release/v1

    - name: Post status to Slack
      if: ${{ success() }}
      uses: ravsamhq/notify-slack-action@2.5.0
      with:
        status: ${{ needs.build-and-test.result == 'success' && 'success' || 'failure' }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.NOTIFY_SLACK_ACTION_WEBHOOK_URL }}

    - name: Post failure to Slack
      if: ${{ failure() || cancelled() }}
      uses: ravsamhq/notify-slack-action@2.5.0
      with:
        status: 'failure'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.NOTIFY_SLACK_ACTION_WEBHOOK_URL }}
