name: Test installability of Python Package

on:
  schedule:
    # Run on Fridays at 05:00 UTC
    - cron: '0 5 * * 5'
  workflow_dispatch:

jobs:
  test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
      fail-fast: true

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install the current SDK version from PyPI
      run: |
        VERSION=$(<VERSION)
        pip install exabel-data-sdk==$VERSION --no-cache-dir

    - name: Post to Slack
      uses: ravsamhq/notify-slack-action@2.5.0
      if: failure()
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.NOTIFY_SLACK_ACTION_WEBHOOK_URL }}
